import Head from 'next/head'
import Image from 'next/image'
import axios from "axios";
import styles from '../styles/Home.module.css'
import Hat1 from '../public/hat/hat1.png'
import Hat2 from '../public/hat/hat2.png'
import Hat3 from '../public/hat/hat3.png'
import Hat4 from '../public/hat/hat4.png'
import Hat5 from '../public/hat/hat5.png'
import Hat6 from '../public/hat/hat6.png'
import Hat7 from '../public/hat/hat7.png'
import Hat8 from '../public/hat/hat8.png'
import Hat9 from '../public/hat/hat9.png'
import Hat10 from '../public/hat/hat10.png'
import Hat11 from '../public/hat/hat11.png'
import Hat12 from '../public/hat/hat12.png'
import Hat13 from '../public/hat/hat13.png'
import Hat14 from '../public/hat/hat14.png'
import { useEffect, useState } from 'react'
import { useRouter } from "next/router";

export default function DressingRoom() {
  const [submitLoder, setSubmitLoder] = useState()
  const [hat, sethat] = useState("")
  const [hair, sethair] = useState("")
  const [glasse, setglasse] = useState("")
  const [ear, setear] = useState("")
  const [nose, setnose] = useState("")
  const [jacket, setjacket] = useState("")
  const [imageShow, setImageShow] = useState(false)

  const router = useRouter();
  const data = router.query;
  console.log(data);
  
  var tokenID = 11
  let Hats = [
    {
      id: '1',
      name: 'Hat1',
      img: Hat1
    },
    {
      id: '2',
      name: 'Hat2',
      img: Hat2
    },
    {
      id: '3',
      name: 'Hat3',
      img: Hat3
    },
    {
      id: '4',
      name: 'Hat4',
      img: Hat4
    },
    {
      id: '5',
      name: 'Hat5',
      img: Hat5
    },
    {
      id: '6',
      name: 'Hat6',
      img: Hat6
    },
    {
      id: '7',
      name: 'Hat7',
      img: Hat7
    },
    {
      id: '8',
      name: 'Hat8',
      img: Hat8
    },
    {
      id: '9',
      name: 'Hat9',
      img: Hat9
    },
    {
      id: '10',
      name: 'Hat10',
      img: Hat10
    },
    {
      id: '11',
      name: 'Hat11',
      img: Hat11
    },
    {
      id: '12',
      name: 'Hat12',
      img: Hat12
    },
    {
      id: '13',
      name: 'Hat13',
      img: Hat13
    },
    {
      id: '14',
      name: 'Hat14',
      img: Hat14
    }
  ]
  const setLayer = async (
    Phat,
    Phair,
    Pglasse,
    Pear,
    Pnose,
    Pjacket,
  ) => {
    var Fhat = Phat
    console.log("🚀 ~ file: index.js ~ line 111 ~ Home ~ Fhat", Fhat)
    var Fhair = Phair
    var Fglasse = Pglasse
    var Fear = Pear
    var Fnose = Pnose
    var Fjacket = Pjacket

    // fetch(`https://gateway.pinata.cloud/ipfs/Qmb67z2o9yKuDQZneZGQktZMFhxVkdMTGm2X9F1EaE2ojR/${tokenID}.json`)
    //         .then((response) => console.log("Metadata", response));
    const response = await fetch(`https://gateway.pinata.cloud/ipfs/Qmb67z2o9yKuDQZneZGQktZMFhxVkdMTGm2X9F1EaE2ojR/${tokenID}.json`);
    // waits until the request completes...
    const details = await response.json();
    console.log("🚀 ~ file: index.js ~ line 139 ~ Home ~ details", details.attributes[0].value)
    var background = details.attributes[0].value;

    // data.append('Background', background);
    // data.append('Hat', Fhat);
    // data.append('Hair', Fhair);
    // data.append('Glasses', Fglasse);
    // data.append("Ear", Fear);
    // data.append("Nose", Fnose);
    // data.append('Jacket', Fjacket);
    // data.append('tokenID', tokenID);
    var data = Object();

    data.Background = background
    data.Hat = Fhat;
    data.Hair = Fhair;
    data.Glasses = Fglasse;
    data.Ear = Fear;
    data.Nose = Fnose;
    data.Jacket = Fjacket;
    data.tokenID = tokenID;

    console.log("data", data);
    var config = {
      method: 'post',
      url: `http://localhost:3001/api/setlayer`,
      data: data,
    };

    axios(config)
      .then(function (response) {
        console.log(JSON.stringify(response.data));
        setTimeout(() => {
          fetch(`http://localhost:3001/assets/${tokenID}.gif`)
            .then((response) => console.log("In fetch", response));
          setSubmitLoder(false)
          setImageShow(true)

        }, 1000);
      })
      .catch(function (error) {
        console.log(error);
      });

  }
  async function submitHandle() {
    setSubmitLoder(true)
    setImageShow(false)
    setLayer(
      hat,
      hair,
      glasse,
      ear,
      nose,
      jacket,

    )

  }
  function setState(e) {
    console.log("🚀 ~ file: index.js ~ line 179 ~ setState ~ e", e)

  }
  return (
    <div className="background m-0 p-0">
      <Head>
        <title>Knowlytes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <p className='text-center wl_text pt-5'>
        Welcome to Dressing Room
      </p>

      {/* <div className="container-fluid">
        <div className="row">
          { 
            Hats.map((e, i) => {
              return(
              <div className='col-2 d-flex justify-content-center'>
                <div className="card card_size me-2 mt-2 mb-2"  >
                  <Image
                    className="card-img img-fluid"
                    src={e.img}
                  />
                  <div className="card-body">
                    <h5 className="card-title text-center card_text">{e.name}</h5>
                  </div>
                </div>
              </div>
              )
            })
          }

        </div>
      </div> */}

      <div className="container" id="login-container">

        <div className="row mx-auto">
          <form id="form" onSubmit={submitHandle}>
            <div className="row d-flex justify-content-between ">

              <div className="col-md-4 col-sm-4 mx-auto" >



                <div className="form-group mb-3">
                  <label htmlFor="floatingInput"
                    className='wl_text1'>Hat Name</label>
                  <select className="form-select" aria-label="Default select example"
                    onChange={(e) => sethat(e.target.value || null)}>
                    <option defaultValue=" ">Select Hat</option>
                    <option value="Hat1">Hat1</option>
                    <option value="Hat2">Hat2</option>
                    <option value="Hat3">Hat3</option>
                    <option value="Hat4">Hat4</option>
                    <option value="Hat5">Hat5</option>
                    <option value="Hat6">Hat6</option>
                    <option value="Hat7">Hat7</option>
                    <option value="Hat8">Hat8</option>
                    <option value="Hat9">Hat9</option>
                    <option value="Hat10">Hat10</option>
                    <option value="Hat11">Hat11</option>
                    <option value="Hat12">Hat12</option>
                    <option value="Hat13">Hat13</option>
                    <option value="Hat14">Hat14</option>
                  </select>
                  {/* <input type="text" className="form-control"
                    placeholder="Hat Name"
                    name="" id="name"
                    onChange={(e) => sethat(e.target.value)}
                  ></input> */}
                </div>
                <div className="form-group mb-3">
                  <label htmlFor="floatingInput" className='wl_text1'>Hair Name</label>

                  <select className="form-select" aria-label="Default select example"
                    onChange={(e) => sethair(e.target.value || null)}>
                    <option defaultValue=" ">Select Hair</option>
                    <option value="Hair1">Hair1</option>
                    <option value="Hair2">Hair2</option>
                    <option value="Hair3">Hair3</option>
                    <option value="Hair4">Hair4</option>
                    <option value="Hair5">Hair5</option>
                    <option value="Hair6">Hair6</option>
                    <option value="Hair7">Hair7</option>
                    <option value="Hair8">Hair8</option>
                    <option value="Hair9">Hair9</option>
                    <option value="Hair10">Hair10</option>
                    <option value="Hair11">Hair11</option>
                    <option value="Hair12">Hair12</option>
                    <option value="Hair13">Hair13</option>
                  </select>
                  {/* <input type="text" className="form-control"
                    placeholder="Hair Name"
                    name="" id="name"
                    onChange={(e) => sethair(e.target.value)}
                  ></input> */}
                </div>
                <div className="form-group mb-3">
                  <label htmlFor="floatingInput" className='wl_text1'>Glasse Name</label>
                  <select className="form-select" aria-label="Default select example"
                    onChange={(e) => setglasse(e.target.value || null)}>
                    <option defaultValue=" ">Select Glasses</option>
                    <option value="Glasses1">Glasses1</option>
                    <option value="Glasses2">Glasses2</option>
                    <option value="Glasses3">Glasses3</option>
                    <option value="Glasses4">Glasses4</option>
                    <option value="Glasses5">Glasses5</option>
                    <option value="Glasses6">Glasses6</option>
                    <option value="Glasses7">Glasses7</option>
                    <option value="Glasses8">Glasses8</option>
                  </select>
                  {/* <input type="text" className="form-control"
                    placeholder="Glasse Name"
                    name="" id="name"
                    onChange={(e) => setglasse(e.target.value)}
                  ></input> */}
                </div>
                <div className="form-group mb-3">
                  <label htmlFor="floatingInput" className='wl_text1'>Ear Name</label>
                  <select className="form-select" aria-label="Default select example"
                    onChange={(e) => setear(e.target.value || null)}>
                    <option defaultValue=" ">Select Ear</option>
                    <option value="Ear1">Ear1</option>
                    <option value="Ear2">Ear2</option>
                    <option value="Ear3">Ear3</option>
                    <option value="Ear4">Ear4</option>
                    <option value="Ear5">Ear5</option>
                    <option value="Ear6">Ear6</option>
                    <option value="Ear7">Ear7</option>
                    <option value="Ear8">Ear8</option>
                  </select>
                  {/* <input type="text" className="form-control"
                    placeholder="Ear Name"
                    name="" id="name"
                    onChange={(e) => setear(e.target.value)}
                  ></input> */}
                </div>
                <div className="form-group mb-3">
                  <label htmlFor="floatingInput" className='wl_text1'>Nose Name</label>
                  <select className="form-select" aria-label="Default select example"
                    onChange={(e) => setnose(e.target.value || null)}>
                    <option defaultValue=" ">Select Nose</option>
                    <option value="Nose1">Nose1</option>
                    <option value="Nose2">Nose2</option>
                    <option value="Nose3">Nose3</option>
                    <option value="Nose4">Nose4</option>
                    <option value="Nose5">Nose5</option>
                    <option value="Nose6">Nose6</option>
                    <option value="Nose7">Nose7</option>
                    <option value="Nose8">Nose8</option>
                  </select>
                  {/* <input type="text" className="form-control"
                    placeholder="Nose Name"
                    name="" id="name"
                    onChange={(e) => setnose(e.target.value)}
                  ></input> */}
                </div>
                <div className="form-group mb-3">
                  <label htmlFor="floatingInput" className='wl_text1'>Jacket Name</label>
                  <select className="form-select" aria-label="Default select example"
                    onChange={(e) => setjacket(e.target.value || null)}>
                    <option defaultValue=" ">Select Jacket</option>
                    <option value="Jacket1">Jacket1</option>
                    <option value="Jacket2">Jacket2</option>
                    <option value="Jacket3">Jacket3</option>
                    <option value="Jacket4">Jacket4</option>
                    <option value="Jacket5">Jacket5</option>
                    <option value="Jacket6">Jacket6</option>
                    <option value="Jacket7">Jacket7</option>
                    <option value="Jacket8">Jacket8</option>
                    <option value="Jacket9">Jacket9</option>
                    <option value="Jacket10">Jacket10</option>
                    <option value="Jacket11">Jacket11</option>
                    <option value="Jacket12">Jacket12</option>
                    <option value="Jacket13">Jacket13</option>
                    <option value="Jacket14">Jacket14</option>
                  </select>
                  {/* <input type="text" className="form-control"
                    placeholder="Jacket Name"
                    name="" id="name"
                    onChange={(e) => setjacket(e.target.value)}
                  ></input> */}
                </div>
                <button type="button"
                  className="btn btn-light save-button btn-lg btn-block mb-5"
                  onClick={submitHandle}>
                  {submitLoder === true ?
                    <span className="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                    : ""}
                  submit</button>
              </div>


              <div className="col-md-4 mt-2  mx-auto">
                <p className='text-center wl_text2'>
                  Preview Image
                </p>
                {imageShow === true ?
                  <img
                    className="img-fluid"
                    src={`http://localhost:3001/assets/${tokenID}.gif`}
                  />
                  : ''}
              </div>


            </div>
          </form>
        </div>
        {/* <div className='row mx-auto'>
          {imageShow === true ?
            <div className="col-md-4 mb-5  mx-auto">
              <img
                className="img-fluid"
                src={`http://localhost:3001/assets/${tokenID}.gif`}
              />
            </div>
            : ''}
        </div> */}
      </div>

    </div>

  )
}
