import Header from "./Header";
import Head from 'next/head'

export default function Main({ children }) {
    return (
        <>
        <div>
        <Head>
                <title>Knowlytes</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <Header />
            <main >
                {children}
            </main>
        </div>
        </>
    )
}
